### ISSUE TITLE
Error trying compile DLL

### ISSUE THREAD

**Issue by Geromo94** [juanmjacobs/il2cpp-modder#20]
Hello, can you help me? I trying compile Visual Studio 2019 and get error :C

Error: E0081, C4430

Screenshot: https://prnt.sc/22skr6w

**Comment by juanmjacobs** [comment]
hi! the link for the screenshot is down

**Comment by Geromo94** [comment]
Sorry, link: https://imgur.com/a/qQD4hbt

I trying compile project "gameModder" for x64 Game. It still work?

**Comment by juanmjacobs** [comment]
Hi! sadly il2cpp-modder does not work for 64 bits games. I don't really know why, but some smart people here have noticed that already.
As per your compile errors, I do not understand the language from the error messages =(
Check if you have imported the files correctly and look for a broken include. Also be sure to follow the [compiling steps](https://github.com/juanmjacobs/il2cpp-modder/blob/main/doc/usage.md#compiling)
