### ISSUE TITLE
Error 'Process not found'

### ISSUE THREAD

**Issue by oxi-dev0** [juanmjacobs/il2cpp-modder#22]
Im getting the error `Process not found yet for executable Game`. Does anyone know why this is? The exe of the game is running when i run `injector.exe`

**Comment by oxi-dev0** [comment]
The console closes after printing this message

**Comment by oxi-dev0** [comment]
After debugging, it seems `GetProcId(procName);` is causing the crash

**Comment by oxi-dev0** [comment]
![image](https://user-images.githubusercontent.com/33568643/147472274-6755f913-e683-4bd9-b071-9ffdec57ba15.png)
It is getting to `injected`, But isnt a 'debug' window meant to appear?

**Comment by oxi-dev0** [comment]
![image](https://user-images.githubusercontent.com/33568643/147472337-742075df-ed85-425b-abe1-0a9f405c816e.png)
It prints `injected` but no 'modding' console appears :/

**Comment by juanmjacobs** [comment]
Hi!
- Have you defined any [modding rules](https://github.com/juanmjacobs/il2cpp-modder/blob/main/doc/rules.md)?
- Maybe try running the game as admin?
- Is there some antivirus interfering? Remember this hack is super basic, i'd not be surprised if an antivirus would block it from executing.

**Comment by oxi-dev0** [comment]
Thanks for your response! I realised i forgot to change the Trampoline Hook value, I will try it now

**Comment by juanmjacobs** [comment]
Cool, let me know!
