### ISSUE TITLE
how to install and use it properly?

### ISSUE THREAD

**Issue by carmenporko** [juanmjacobs/il2cpp-modder#23]
hey, how to install and use it on windows 11? can you make video tutorial? thanks

**Comment by juanmjacobs** [comment]
Hi, how are you? At the moment I do not have access to any device with Windows 11.

The steps for installation are in the README https://github.com/juanmjacobs/il2cpp-modder#installation. If you can't run `.sh` scripts, that's ok, just follow this steps:
1) Clone the repo `git clone https://github.com/juanmjacobs/il2cpp-modder`
2) Enter the project `cd il2cpp-modder`
3) Install project dependencies `npm install`
4) Add il2cpp-modder to your system as a global executable `npm install -g .`

And you are good to go!

All usage documentation is also linked from the main README. If you'd like to make a video tutorial, I'd be happy to include it!
