### ISSUE TITLE
How to make it works with android unity games?

### ISSUE THREAD

**Issue by carmenporko** [juanmjacobs/il2cpp-modder#24]
Hey, your project is good but it seems to only work on pc unity games. How to make it works on Android unity games?

**Comment by lrutjens** [comment]
does it not work with them?

**Comment by lrutjens** [comment]
Idk I haven’t tried yet

**Comment by juanmjacobs** [comment]
Hi there @carmenporko! sorry for the delay, my focus is not on this project lately. 

Sadly, it doesn't work on android games. The whole thing is based on DLL injection, which doesn't apply to Android at all. If you want to give it a go, I'd be happy to give you some pointers.
